### ISSUE TITLE
GDPR right to be forgotten

### ISSUE THREAD

**Issue by snocke** [stackabletech/stackablectl#153]
### Scenario:
Event data from your E-Commerce Webshop is stored in hbase.
Details of your data and master data is stored somewhere else.
Questions around this are usual:

- how can I connect the data?
- how can I easily manipulate the data? 

Therefore, analyzing the event data can result in an additional ETL job and using up more space. Since event data can get very large you may need to aggregate the data and thus lose details.
Another challenge in context of event data from a webshop results from the GDPR context

A customer enforces his right to be forgotten and wants all his data deleted.
With hbase, you have access to a single row. Thus, a company is able to quickly find the customer, the events connect with the customer and master data.
Customers won't store all there data in hbase. Thus they need to query different sources to get a big picture of the situation. This demo will try to connect event data stored in hbase with data stored in s3 to enrich the events (data federation).

As of now, we need to introduce ACL on the hbase side. Therefore, we can not execute the deletion query. This will be possible with a future enhancement of the demo.
Another future development could be modeling the data as a data vault and applying data warehouse concepts.

### Tasks:

- [x] Find suitable clickstream data
- [x] Setup Stack HDFS, Hbase, Phoenix, Trino
- [x] Create load job to import data from nexus to minio
- [x] Create load job to import the hbase relevant data to hdfs
- [x] Create job that load file from s3
- [x] Create script to transform s3 file and add hbse-row-key. We want to create a hash derived from the content. Thus, we have a key working in every "world"
- [x] Upload new file with hbase-row-key to s3
- [x] find a good way to load data to hbase, create table/view in phoenix and have it available in trino (trino-phoenix-connector) 
- [x] create view in phoenix
- [x] create trino views with hashes that makes the data joinable
- [x] test query federation
- [x] Query data and delete rows (deletion won't be possible at this point in time. Need ACLs working on hbase site.

**Comment by snocke** [comment]
For release we need the following issues:

https://github.com/stackabletech/trino-operator/issues/331
https://github.com/stackabletech/hbase-operator/issues/289
https://github.com/stackabletech/hbase-operator/issues/288

**Comment by lfrancke** [comment]
We have row level deletes in the trino iceberg demo which demonstrates what we wanted to achieve here, closing
