### ISSUE TITLE
Data Lakehouse Demo

### ISSUE THREAD

**Issue by Jimvin** [stackabletech/stackablectl#86]
Data warehouse is a valuable demo as we hope to see significant customer adoption of this pattern.

## Aims
- Build a data warehouse based on Stackable Data Platform
- Introduce best practice and define a supported architecture for DWH
- Show ingestion with NiFi as well as SQL DWH

## Tasks
- [ ] Find a suitable data set e.g. sales + product + finance data
- [ ] Stackable cluster configuration
- [ ] Load data into S3 (minio) using NiFi
- [ ] Create Trino tables and views (data modelling)
- [ ] Create a visualisation using Trino and SuperSet

**Comment by fhennig** [comment]
We have a lakehouse demo now: https://docs.stackable.tech/home/stable/demos/data-lakehouse-iceberg-trino-spark

i'm closing this ticket
